using UnityEngine;

namespace ThermalTail
{
    /// <summary>
    /// Runtime dressing for the ground-plane build: a floor, an edge wall, a key light and
    /// distance fog.
    ///
    /// Built in code rather than authored into the seven level scenes on purpose. The scenes
    /// are generated by TTLevelImporter from the browser build's level data, so anything
    /// hand-placed in them is lost the next time a level is re-imported. Everything here is
    /// derived from LevelSettings, so it survives a re-import and costs the designer nothing.
    /// </summary>
    [DisallowMultipleComponent]
    public class ThermalWorld3D : MonoBehaviour
    {
        public Color FloorColor = new Color(0.26f, 0.29f, 0.33f);
        public Color WallColor = new Color(0.17f, 0.19f, 0.23f);
        public Color FogColor = new Color(0.07f, 0.09f, 0.13f);
        public float WallHeight = 2.4f;
        [Tooltip("How far below the decks the unreachable base sits, on levels made of islands.")]
        public float VoidDepth = 9f;
        public Color VoidColor = new Color(0.04f, 0.05f, 0.07f);

        /// <summary>Build the floor, edge wall and lighting for a level. Safe to call again.</summary>
        public static ThermalWorld3D Build(LevelSettings settings, bool solidFloor = true)
        {
            if (settings == null) return null;

            var existing = FindFirstObjectByType<ThermalWorld3D>();
            if (existing != null) Discard(existing.gameObject);

            var root = new GameObject("World 3D (runtime)");
            var world = root.AddComponent<ThermalWorld3D>();
            world.Construct(settings, solidFloor);
            return world;
        }

        void Construct(LevelSettings settings, bool solidFloor)
        {
            float w = Mathf.Max(1f, settings.Width) / TTCoord.PixelsPerUnit;
            float h = Mathf.Max(1f, settings.Height) / TTCoord.PixelsPerUnit;
            Vector3 centre = TTCoord.RectCenter(0f, 0f, settings.Width, settings.Height, 0f);

            // Ground runs past the play area so the chase camera has somewhere to stand
            // behind a lizard that spawns on the edge. See TTView.ArenaApron.
            float apron = TTView.ArenaApron * 2f;

            var floorMat = MakeMaterial(FloorColor, 0.92f);
            var wallMat = MakeMaterial(WallColor, 0.85f);

            // Floor as a thin slab rather than a quad: a quad is single sided, so it turns
            // black the moment anything looks at it from the wrong side, and a slab also
            // takes the fog and the key light the same way the rest of the greybox does.
            // Its top face sits exactly on y = 0, which is what every height here assumes.
            //
            // A side-authored level has no continuous floor at all - its decks are islands
            // over open air - so the slab drops far below as an unreachable base. Draw it at
            // y = 0 there and every pit would look like solid ground you cannot fall through.
            const float slab = 0.4f;
            float floorTop = solidFloor ? 0f : -VoidDepth;
            var floor = GameObject.CreatePrimitive(PrimitiveType.Cube);
            floor.name = solidFloor ? "Floor" : "Void Base";
            floor.transform.SetParent(transform, false);
            floor.transform.position = centre + Vector3.up * (floorTop - slab * 0.5f);
            floor.transform.localScale = new Vector3(w + apron, slab, h + apron);
            Strip(floor, solidFloor ? floorMat : MakeMaterial(VoidColor, 0.98f));

            // Edge wall, at the apron's rim so it never stands between camera and lizard.
            // Levels made of islands get no wall at all: the drop is already the boundary,
            // and a fence ringing empty air just reads as a mistake.
            if (solidFloor)
            {
                const float t = 0.35f;
                float ew = w + apron, eh = h + apron;
                AddWall("Wall N", centre + new Vector3(0f, WallHeight * 0.5f, eh * 0.5f), new Vector3(ew + t, WallHeight, t), wallMat);
                AddWall("Wall S", centre + new Vector3(0f, WallHeight * 0.5f, -eh * 0.5f), new Vector3(ew + t, WallHeight, t), wallMat);
                AddWall("Wall E", centre + new Vector3(ew * 0.5f, WallHeight * 0.5f, 0f), new Vector3(t, WallHeight, eh + t), wallMat);
                AddWall("Wall W", centre + new Vector3(-ew * 0.5f, WallHeight * 0.5f, 0f), new Vector3(t, WallHeight, eh + t), wallMat);
            }

            ApplyLighting();
        }

        void AddWall(string label, Vector3 pos, Vector3 scale, Material mat)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
            go.name = label;
            go.transform.SetParent(transform, false);
            go.transform.position = pos;
            go.transform.localScale = scale;
            Strip(go, mat);
        }

        /// <summary>
        /// Destroy that also works outside play mode, so a screenshot or an editor preview
        /// can build the dressing without Unity complaining about the deferred path.
        /// </summary>
        static void Discard(Object target)
        {
            if (target == null) return;
            if (Application.isPlaying) Destroy(target);
            else DestroyImmediate(target);
        }

        /// <summary>Nothing here is simulated, so the primitive colliders are dead weight.</summary>
        static void Strip(GameObject go, Material mat)
        {
            var col = go.GetComponent<Collider>();
            if (col != null) Discard(col);
            var rend = go.GetComponent<Renderer>();
            if (rend != null && mat != null)
            {
                rend.sharedMaterial = mat;
                rend.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.On;
            }
        }

        static Material MakeMaterial(Color colour, float smoothnessInverted)
        {
            var shader = Shader.Find("Universal Render Pipeline/Lit")
                         ?? Shader.Find("Universal Render Pipeline/Unlit")
                         ?? Shader.Find("Standard");
            if (shader == null)
            {
                Debug.LogWarning("[ThermalWorld3D] no usable lit shader found; floor will fall back to the primitive default.");
                return null;
            }

            var mat = new Material(shader);
            mat.SetColor("_BaseColor", colour);
            mat.SetColor("_Color", colour);
            if (mat.HasProperty("_Smoothness")) mat.SetFloat("_Smoothness", 1f - smoothnessInverted);
            if (mat.HasProperty("_Glossiness")) mat.SetFloat("_Glossiness", 1f - smoothnessInverted);
            return mat;
        }

        void ApplyLighting()
        {
            RenderSettings.fog = true;
            RenderSettings.fogMode = FogMode.Linear;
            RenderSettings.fogColor = FogColor;
            RenderSettings.fogStartDistance = 22f;
            RenderSettings.fogEndDistance = 70f;
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(0.34f, 0.39f, 0.47f);
            RenderSettings.ambientEquatorColor = new Color(0.24f, 0.27f, 0.32f);
            RenderSettings.ambientGroundColor = new Color(0.14f, 0.15f, 0.18f);

            // The generated scenes ship one directional light; angle it so the extruded
            // greybox actually casts, which is most of what sells the third dimension.
            var key = FindFirstObjectByType<Light>();
            if (key == null)
            {
                var go = new GameObject("Key Light");
                go.transform.SetParent(transform, false);
                key = go.AddComponent<Light>();
                key.type = LightType.Directional;
            }
            if (key.type == LightType.Directional)
            {
                key.transform.rotation = Quaternion.Euler(52f, 145f, 0f);
                key.color = new Color(0.85f, 0.90f, 1f);
                key.intensity = 1.6f;
                key.shadows = LightShadows.Soft;
            }
        }
    }
}
